require "Seedr"

puts "First pass:"
puts "First name: #{Seedr.first_name}"
puts "Last name: #{Seedr.last_name}"
puts "Full name: #{Seedr.full_name}"
puts "Middle inital: #{Seedr.middle_initial}"
puts "Username: #{Seedr.username}"
puts "Company name: #{Seedr.company_name}"
puts "email: #{Seedr.email}"
puts "Second pass:"
puts "First name: #{Seedr.first_name}"
puts "Last name: #{Seedr.last_name}"
puts "Full name: #{Seedr.full_name}"
puts "Middle inital: #{Seedr.middle_initial}"
puts "Username: #{Seedr.username}"
puts "Company name: #{Seedr.company_name}"
puts "email: #{Seedr.email}"
puts "random integer: #{Seedr.random_integer}"
puts "random character: #{Seedr.random_string}"
puts "phone number: #{Seedr.phone_number}"
