require "Seedr"

puts ""
puts "Randoms:"
puts "Random integer: #{Seedr.random_integer}"
puts "Random character: #{Seedr.random_string}"
puts "Random integers (8): #{Seedr.random_integer(8)}"
puts "Random characters (8): #{Seedr.random_string(8)}"
puts "Random date: #{Seedr.date}"
puts "Random datetime: #{Seedr.datetime}"
puts ""
puts "Profile:"
puts "First name: #{Seedr.first_name}"
puts "Last name: #{Seedr.last_name}"
puts "Middle inital: #{Seedr.middle_initial}"
puts "Full name: #{Seedr.full_name}"
puts "Username: #{Seedr.username}"
puts "Company name: #{Seedr.company_name}"
puts "Email: #{Seedr.email}"
puts "Phone Number: #{Seedr.phone_number}"
puts "Phone Number (separator): #{Seedr.phone_number('-')}"
puts "Address line 1: #{Seedr.address_line_1}"
puts "Address line 2: #{Seedr.address_line_2}"
puts "City: #{Seedr.city}"
puts "State: #{Seedr.state}"
puts "State (abbreviation): #{Seedr.state(true)}"
puts "Province: #{Seedr.province}"
puts "Province (abbreviation): #{Seedr.province(true)}"
puts "Country: #{Seedr.country}"
puts "Country (abbreviation): #{Seedr.country(true)}"
puts ""
puts "Editorial:"
puts "Category: #{Seedr.category}"
puts "Article type: #{Seedr.article_type}"
puts "Series: #{Seedr.series}"
puts "Title: #{Seedr.title}"
puts "Body: #{Seedr.body}"