require "Seedr"

3.times do
  puts "Random integer(s): #{Seedr.random_integer}"
  puts "Random character(s): #{Seedr.random_string}"
  puts "First name: #{Seedr.first_name}"
  puts "Last name: #{Seedr.last_name}"
  puts "Middle inital: #{Seedr.middle_initial}"
  puts "Full name: #{Seedr.full_name}"
  puts "Username: #{Seedr.username}"
  puts "Company name: #{Seedr.company_name}"
  puts "Email: #{Seedr.email}"
  puts "Address line 1: #{Seedr.address_line_1}"
  puts "Address line 2: #{Seedr.address_line_2}"
  puts "City: #{Seedr.city}"
  puts "State: #{Seedr.state}"
  puts "Province: #{Seedr.province}"
  puts "Country: #{Seedr.country}"
  puts "Country (abbreviation): #{Seedr.country(true)}"
  puts "Phone Number: #{Seedr.phone_number}"
end
